export default {
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
  fontSize: 14,

  display1: {
    'margin-bottom': '.75rem',
    color: '#da0004',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    lineHeight: '1.4em',
    fontSize: '1.4rem',
    fontWeight: 700,
  },
  display2: {
    'margin-bottom': '.5rem',
    color: '#da0004',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    lineHeight: '1.2em',
    fontSize: '1.2rem',
    fontWeight: 700,
  },
  display3: {
    'margin-bottom': '.375rem',
    color: '#333',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    letterSpacing: '-.02em',
    lineHeight: '1.175em',
    fontSize: '1.175rem',
    fontWeight: 600,
  },
  display4: {
    'margin-bottom': '.2rem',
    color: '#666',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    lineHeight: '1.15em',
    fontSize: '1.15rem',
    fontWeight: 600,
  },
  button: {
    textTransform: 'none',
    color: '#FFF',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    fontSize: '1rem',
    fontWeight: 700,
  },
  input: {
    textTransform: 'none',
    color: '#666',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    fontSize: '1rem',
    fontWeight: 400,
  },
  title: {
    color: '#da0004',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    lineHeight: '1.16667em',
    fontSize: '1.3125rem',
    fontWeight: 500,
  },
  subheading: {
    color: '#666',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    lineHeight: '1.5em',
    fontSize: '1rem',
    fontWeight: 400,
  },
  headline: {
    color: '#333',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    lineHeight: '1.35417em',
    fontSize: '1.5rem',
    fontWeight: 400,
  },
  body1: {
    color: '#333',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    lineHeight: '1.4em',
    fontSize: '1rem',
    fontWeight: 400,
  },
  body2: {
    color: '#666',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    lineHeight: '1.3em',
    fontSize: '1rem',
    fontWeight: 700,
  },
  highlight: {
    color: '#da0004',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    lineHeight: '1.4em',
    fontSize: '1rem',
    fontWeight: 600,
  },
  caption: {
    color: '#999',
    fontFamily: '"Nunito", "Helvetica", "Arial", sans-serif',
    lineHeight: '1.375em',
    fontSize: '0.9rem',
    fontWeight: 400,
  },
}
